### ISSUE TITLE
Trying to stream: Segmentation Fault

### ISSUE THREAD

**Issue by zastrixarundell** [flathub/gg.guilded.Guilded#36]
Really interested to try guilded out, but when I try to stream currently I get an application crash. 

```bash
flatpak run gg.guilded.Guilded &> guilded.log
```

When I click start streaming it just crashes.

```
[3:0517/103648.700024:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[10:36:49.059] [info] Checking for update
[3:0517/103649.095291:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0517/103649.095319:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
MESA-LOADER: failed to open zink: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/zink_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
MESA-LOADER: failed to open swrast: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
[10:36:49.677] [info] Update for version 1.0.9199744-release is not available (latest version: 1.0.9199744-release, downgrade is disallowed).
LaunchProcess: failed to execvp:
xdg-settings
[10:36:49.949] [info] n {
  Targets: [
    n { EnabledInDev: true, Name: 'ExperimentAnalysis' },
    n { EnabledInDev: true, Name: 'Counters' },
    n { EnabledInDev: true, Name: 'Verbose' },
    n { EnabledInDev: true, Name: 'ClientSentry' },
    n { EnabledInDev: true, Name: 'LogFile' }
  ],
  IsError: true,
  Dimensions: [ 'errorSource' ],
  Category: 'ErrorEventDefinitions',
  Name: 'DesktopAppError',
  LegacyName: 'DesktopAppError'
} {
  error: TypeError: c.shell.writeShortcutLink is not a function
      at Zr (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:909648)
      at Object._updateShortcutsForNotifications (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:911696)
      at Object.Initialize (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:910108)
      at Jr.Initialize (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:917542)
      at e.Initialize (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:918580)
      at yo.<anonymous> (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:924491)
      at Generator.next (<anonymous>)
      at Generator.i (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:44729)
      at p._promiseFulfilled (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:315682)
      at yo.OnAppReady (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:317735)
      at yo.<anonymous> (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:924218)
      at Generator.next (<anonymous>)
      at Generator.i (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:44729)
      at p._promiseFulfilled (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:315682)
      at yo.<anonymous> (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:317735)
      at yo.Initialize (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:924330)
      at /app/extra/guilded/resources/app.asar/main.js:33:19 {
    extra: {
      errorStringInfo: '{}',
      shortcutPath: '/var/home/zastrix/Desktop/Guilded.lnk',
      errorSource: 'DesktopAppNativeNotifications',
      time: 1684312609930,
      eventSource: 'DesktopApp',
      eventName: 'DesktopAppError',
      viewerPlatform: 'electron',
      viewerAppType: 'Linux',
      deviceId: 'd97f7ae7d5fefdd6a974211dbdae6a230f05e3d754467370f856108caeebd6d9',
      viewerAppVersion: '1.0.9199744-release'
    },
    tags: {
      eventCategory: 'ErrorEventDefinitions',
      eventName: 'DesktopAppError'
    },
    _sentryEventId: null
  },
  shortcutPath: '/var/home/zastrix/Desktop/Guilded.lnk',
  errorSource: 'DesktopAppNativeNotifications',
  time: 1684312609930,
  eventSource: 'DesktopApp',
  eventName: 'DesktopAppError',
  viewerPlatform: 'electron',
  viewerAppType: 'Linux',
  deviceId: 'd97f7ae7d5fefdd6a974211dbdae6a230f05e3d754467370f856108caeebd6d9',
  viewerAppVersion: '1.0.9199744-release'
}
[10:36:49.952] [info] n {
  Targets: [
    n { EnabledInDev: true, Name: 'ExperimentAnalysis' },
    n { EnabledInDev: true, Name: 'Counters' },
    n { EnabledInDev: true, Name: 'Verbose' },
    n { EnabledInDev: true, Name: 'ClientSentry' },
    n { EnabledInDev: true, Name: 'LogFile' }
  ],
  IsError: true,
  Dimensions: [ 'errorSource' ],
  Category: 'ErrorEventDefinitions',
  Name: 'DesktopAppError',
  LegacyName: 'DesktopAppError'
} {
  error: TypeError: c.shell.writeShortcutLink is not a function
      at Zr (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:909648)
      at Object._updateShortcutsForNotifications (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:911696)
      at Object.Initialize (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:910108)
      at Jr.Initialize (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:917542)
      at e.Initialize (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:918580)
      at yo.<anonymous> (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:924491)
      at Generator.next (<anonymous>)
      at Generator.i (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:44729)
      at p._promiseFulfilled (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:315682)
      at yo.OnAppReady (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:317735)
      at yo.<anonymous> (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:924218)
      at Generator.next (<anonymous>)
      at Generator.i (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:44729)
      at p._promiseFulfilled (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:315682)
      at yo.<anonymous> (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:317735)
      at yo.Initialize (/app/extra/guilded/resources/app.asar/electron/electronApp.js:1:924330)
      at /app/extra/guilded/resources/app.asar/main.js:33:19 {
    extra: {
      errorStringInfo: '{}',
      shortcutPath: '/var/home/zastrix/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Guilded.lnk',
      errorSource: 'DesktopAppNativeNotifications',
      time: 1684312609941,
      eventSource: 'DesktopApp',
      eventName: 'DesktopAppError',
      viewerPlatform: 'electron',
      viewerAppType: 'Linux',
      deviceId: 'd97f7ae7d5fefdd6a974211dbdae6a230f05e3d754467370f856108caeebd6d9',
      viewerAppVersion: '1.0.9199744-release'
    },
    tags: {
      eventCategory: 'ErrorEventDefinitions',
      eventName: 'DesktopAppError'
    },
    _sentryEventId: null
  },
  shortcutPath: '/var/home/zastrix/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Guilded.lnk',
  errorSource: 'DesktopAppNativeNotifications',
  time: 1684312609941,
  eventSource: 'DesktopApp',
  eventName: 'DesktopAppError',
  viewerPlatform: 'electron',
  viewerAppType: 'Linux',
  deviceId: 'd97f7ae7d5fefdd6a974211dbdae6a230f05e3d754467370f856108caeebd6d9',
  viewerAppVersion: '1.0.9199744-release'
}
[3:0517/103649.954875:ERROR:bus.cc(562)] Failed to get the ownership of org.kde.StatusNotifierItem-3-1: org.freedesktop.DBus.Error.ServiceUnknown
load_input_helper [1918]: Using XFree86 keyboard layout.
load_input_helper [1920]: XKB support is required to accurately determine keyboard characters!
[0517/103656.440884:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/guilded: line 8:     3 Segmentation fault      (core dumped) env TMPDIR="$XDG_CACHE_HOME" zypak-wrapper /app/extra/guilded/guilded "$FLAGS" "$@"
```

https://github.com/flathub/gg.guilded.Guilded/assets/30195425/cfa9a276-c3f1-47d1-8446-44bad73156d0

**Comment by losuler** [comment]
Looks like the cause of this crash is Wayland, because it doesn't crash in X11. I tested this with and without Flatpak (on Fedora and Ubuntu). You'll have to wait for the Guilded developers to fix this (which is possible because Discord doesn't crash), or just use X11 in the meantime.

I'll leave this issue open until this gets fixed, so others can get notified once it has been.

**Comment by zastrixarundell** [comment]
Just for more info, this happens on both an Nvidia and integrated Intel GPU under Wayland so it's not an Nvidia-only issue.

**Comment by LegitGreenBoi** [comment]
> Just for more info, this happens on both an Nvidia and integrated Intel GPU under Wayland so it's not an Nvidia-only issue.

It also happens on AMD GPUs under Wayland
